# Generated by Django 3.0.3 on 2020-07-09 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('age', models.FloatField(default=0)),
                ('redshift', models.FloatField(default=0)),
                ('dark_matter_in_group', models.IntegerField(default=0)),
                ('gas_in_group', models.IntegerField(default=0)),
                ('stars', models.IntegerField(default=0)),
                ('back_holes', models.IntegerField(default=0)),
                ('fof_groups', models.IntegerField(default=0)),
                ('folder_size', models.IntegerField(default=0)),
                ('pig_folder_size', models.IntegerField(default=0)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bluetides.Simulation')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bluetides.Snapshot')),
            ],
        ),
        migrations.CreateModel(
            name='FofGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('folder_size', models.IntegerField(default=0)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fof_group_set', to='bluetides.Snapshot')),
            ],
        ),
    ]
