# Generated by Django 3.0.3 on 2020-08-11 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bluetides', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snapshot',
            old_name='back_holes',
            new_name='black_holes',
        ),
    ]
