# Generated by Django 3.0.3 on 2020-08-24 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bluetides', '0002_auto_20200811_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snapshot',
            name='pig_folder_size',
        ),
        migrations.AddField(
            model_name='snapshot',
            name='lookback',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='species',
            name='folder_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='species',
            name='species_type',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='species',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='species_set', to='bluetides.Snapshot'),
        ),
    ]
