# Generated by Django 3.0.3 on 2020-08-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluetides', '0003_auto_20200824_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fofgroups',
            name='folder_size',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='folder_size',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='species',
            name='folder_size',
            field=models.FloatField(default=0),
        ),
    ]
