# Generated by Django 2.2.5 on 2020-07-31 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endpoint',
            old_name='descriptio',
            new_name='description',
        ),
    ]
