# Generated by Django 2.2.5 on 2020-08-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapps', '0003_auto_20200813_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='arguments',
            field=models.ManyToManyField(blank=True, to='webapps.Argument'),
        ),
    ]
